name: HTMLProofer

on:
  push:
    branches: [ LSW, PYH, LKZ, TKM, LJE ]
  pull_request:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HTMLProofer
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: "./"
